---
title: "Logistics🏕️🗺️"
format: html
date: 2024/04/10
date-format: long
date-modified: last-modified
editor: 
  markdown: 
    wrap: sentence
---

## Venue🏡 and Accommodation🛌

The school will take place in n the charming spa town of [Mariánské Lázně](https://en.wikipedia.org/wiki/Mari%C3%A1nsk%C3%A9_L%C3%A1zn%C4%9B) (Czech Republic). Specifically, our Science School will take place at [Hlavní tř. 389/14, 353 01 Mariánské Lázně 1](https://maps.app.goo.gl/evZZP1S8eURq44ju6).

## Food🍱

The organisers will provide main meals (breakfast, lunch and dinner) for free as part of the Science School.

::: callout-warning
### Dietary preferences

If you have any dietary preferences and/or restrictions (vegetarian/vegan/...), please let us know in advance.
:::

## Travel🚗

**The participants are expected to organize their travel**.

If you are arriving by train, the venue is about a 35-minute walk from the station. Alternatively, local buses can take you part of the way (line number 115/116).

Should you arrive before the organizing team, feel free to already check in at the reception and collect the keys to your assigned room. Please remember to **bring your ID or passport**, as it will be required for the accommodation check-in. **Non-EU citizens must bring their passport**.

Since it’s hard to think on an empty stomach, the first item on our agenda will be a shared lunch at 12:00. Please make sure you arrive on time.

### Arrival and Departure 🚆🚍:

Your arrival date is Monday, 15th September 2025. Please plan your travel accordingly, so that you arrive in time for lunch at 12:00. The Science School will start with an introduction and welcome session at 13:00.

The Science School will end on Saturday, 20st September 2025. The final day will finish with excursion, which will end around 15:00, after which you can start your journey back home.

### Reimbursement of travel costs 💸:

For the reimbursement, you will need your German tax ID (which you hopefully applied for in time, see reimbursement info email -  we have already received the first tax ID’s of yours.) Additionally, you need to submit the original invoices for all your travel expenses. So please make sure you bring them with you, and if possible, print out receipts for e-tickets and such. During the science school, we will hold a small “How-to-reimbursement” workshop, to guide you through completing the reimbursement form correctly.

## What to bring🎒

::: callout-tip
## We recommend to pack

-   **Laptop** + **charger**
-   **Toiletries**
-   **Personal medicine if needed**
-   **Warm clothes**
-   **Hiking shoes**/**Raincoat** (especially if you want to join us for the excursion)
-   You can bring your own **snacks** and **drinks**
-   **Water bottle**
-   **Games** or **music instrument** for social activities
-   **Money in cash** (CZK; There is an option to go to ATM in Mariánské Lázně, but it might not be available at the venue)
-   **reimbursement of travel costs** (Invoices of your travel tickets to and from the Science School, if possible already printed, and your bank account details)
-   **Good mood**🥳
:::