---
title: "Program📅"
format: html
date: 2024/04/10
date-format: long
date-modified: last-modified
editor: 
  markdown: 
    wrap: sentence
---

## Preliminary Program 2026


<!-- The excursion was moved to Thursday due to the weather forecast. -->

| Time | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
|:---:|:---|:---|:---|:---|:---|:---|
| 8:00 - 9:00 | \- | Breakfast | Breakfast | Breakfast | Breakfast | Breakfast |
| 9:00 - 10:30 | Arrival | Our way of R and Reproducibility [🔗](https://github.com/SSoQE/SSoQE-Our_Way_of_R_and_Reproducibility){aria-label="Open the repository for Our way of R and Reproducibility"} | Functional programming in the world of AI [🔗](https://github.com/SSoQE/SSoQE-Functional_Programming_in_the_World_of_AI){aria-label="Open the repository for Functional programming in the world of AI"} | Analysing Community Data [🔗](https://github.com/SSoQE/SSoQE-Analysing_Community_Data){aria-label="Open the repository for Analysing Community Data"} | Project Management and Collaboration (using GitHub) [🔗](https://github.com/SSoQE/SSoQE-Project_Management_and_Collaboration_using_GitHub){aria-label="Open the repository for Project Management and Collaboration (using GitHub)"} | Model-based ordinations [🔗](https://github.com/SSoQE/SSoQE-Model_Based_Ordinations){aria-label="Open the repository for Model-based ordinations"} |
| 10:30 - 11:00 | Arrival | Coffee Break | Coffee Break | Coffee Break | Coffee Break | Coffee Break |
| 11:00 - 12:30 | Arrival | Hypothesis Testing and Null Models [🔗](https://github.com/SSoQE/SSoQE-Hypothesis_Testing_and_Null_Models){aria-label="Open the repository for Hypothesis Testing and Null Models"} | Deep Learning [🔗](https://github.com/SSoQE/SSoQE-Deep_Learning){aria-label="Open the repository for Deep Learning"} | Version Control [🔗](https://github.com/SSoQE/SSoQE-Version_Control){aria-label="Open the repository for Version Control"} | Phylogenetic Data in Ecology [🔗](https://github.com/SSoQE/SSoQE-Phylogenetic_Data_in_Ecology){aria-label="Open the repository for Phylogenetic Data in Ecology"} | Reproducible Analytical Pipelines [🔗](https://github.com/SSoQE/SSoQE-Reproducible_Analytical_Pipelines){aria-label="Open the repository for Reproducible Analytical Pipelines"} |
| 12:30 - 13:15 | Arrival | Lunch | Lunch | Lunch | Lunch | Lunch |
| 13:15 - 14:00 | Arrival | Walk outside | Walk outside | Excursion | Walk outside | Wrap-up & Feedback |
| 14:00 - 16:00 | **!!15:00!!**<br>Welcome and Ice Breaker [🔗](https://github.com/SSoQE/SSoQE-Welcome_and_Ice_Breaker){aria-label="Open the repository for Welcome and Ice Breaker"} | Biodiversity and Richness [🔗](https://github.com/SSoQE/SSoQE-Biodiversity_and_Richness){aria-label="Open the repository for Biodiversity and Richness"} | Exploring Past Vegetation Using Fossil Pollen [🔗](https://github.com/SSoQE/SSoQE-Exploring_Past_Vegetation_Using_Fossil_Pollen){aria-label="Open the repository for Exploring Past Vegetation Using Fossil Pollen"} | Excursion | Phylogenies in Community Ecology [🔗](https://github.com/SSoQE/SSoQE-Phylogenies_in_Community_Ecology){aria-label="Open the repository for Phylogenies in Community Ecology"} | \- |
| 16:00 - 16:30 | Coffee Break | Coffee Break | Coffee Break | Excursion | Coffee Break | \- |
| 16:30 - 18:00 | Species Distribution Modelling [🔗](https://github.com/SSoQE/SSoQE-Species_Distribution_Modelling){aria-label="Open the repository for Species Distribution Modelling"} | Sample Standardisation and Resampling [🔗](https://github.com/SSoQE/SSoQE-Sample_Standardisation_and_Resampling){aria-label="Open the repository for Sample Standardisation and Resampling"} | Biases in Ecological and Paleoecological Data [🔗](https://github.com/SSoQE/SSoQE-Biases_in_Ecological_and_Paleoecological_Data){aria-label="Open the repository for Biases in Ecological and Paleoecological Data"} | Excursion | Ecology of Speciation, Extinction, and Macroevolution [🔗](https://github.com/SSoQE/SSoQE-Ecology_of_Speciation_Extinction_and_Macroevolution){aria-label="Open the repository for Ecology of Speciation, Extinction, and Macroevolution"} | \- |
| 18:00 - 19:00 | Free time | Free time | Free time | Free time | Free time | \- |
| 19:00 - 20:00 | Dinner | Dinner | Dinner | Dinner | Dinner | \- |
| 20:00 - 00:00 | Social | Social | Social | Social | Social | \- |

: {.striped}
